package constant

const ACTIVITY_COMPANY_PROFILE_CREATED = "COMPANY_PROFILE_CREATED"
const ACTIVITY_COMPANY_PROFILE_UPDATED = "COMPANY_PROFILE_UPDATED"
const ACTIVITY_COMPANY_PROFILE_DELETED = "COMPANY_PROFILE_DELETED"

const ACTIVITY_APPLICATION_CREATED = "APPLICATION_CREATED"
const ACTIVITY_APPLICATION_UPDATED = "APPLICATION_UPDATED"
const ACTIVITY_APPLICATION_WITHDRAWN = "APPLICATION_WITHDRAWN"
const ACTIVITY_APPLICATION_DELETED = "APPLICATION_DELETED"

const ACTIVITY_OPPORTUNITY_CREATED = "OPPORTUNITY_CREATED"
const ACTIVITY_OPPORTUNITY_UPDATED = "OPPORTUNITY_UPDATED"
const ACTIVITY_OPPORTUNITY_DELETED = "OPPORTUNITY_DELETED"
