package constant

type Specialisation string

const (
	SPEC_APD  Specialisation = "Architecture Planning and Design"
	SPEC_BCE  Specialisation = "Bio-Chemical Engineering"
	SPEC_BME  Specialisation = "Bio-Medical Engineering"
	SPEC_CER  Specialisation = "Ceramic Engineering"
	SPEC_CHE  Specialisation = "Chemical Engineering"
	SPEC_CHY  Specialisation = "Industrial Chemistry"
	SPEC_CIV1 Specialisation = "Hydraulics and Water Resources Engineering"
	SPEC_CIV2 Specialisation = "Geotechnical Engineering"
	SPEC_CIV3 Specialisation = "Structural Engineering"
	SPEC_CIV4 Specialisation = "Environmental Engineering"
	SPEC_CIV5 Specialisation = "Transportation Engineering"
	SPEC_CIV6 Specialisation = "Engineering Geoscience"
	SPEC_CIV7 Specialisation = "Geoinformatics Engineering"
	SPEC_CSE  Specialisation = "Computer Science and Engineering"
	SPEC_DSE  Specialisation = "Decision Science and Engineering"
	SPEC_ECE1 Specialisation = "Microwave Engineering"
	SPEC_ECE2 Specialisation = "Digital Techniques and Instrumentation"
	SPEC_ECE3 Specialisation = "Microelectronics"
	SPEC_ECE4 Specialisation = "Communication Systems Engineering"
	SPEC_EEE1 Specialisation = "Power Systems"
	SPEC_EEE2 Specialisation = "Electrical Machines and Drive"
	SPEC_EEE3 Specialisation = "Control Systems"
	SPEC_EEE4 Specialisation = "Power Electronics"
	SPEC_EEE5 Specialisation = "Systems Engineering"
	SPEC_MAT  Specialisation = "Mathematics & Computing"
	SPEC_MEC1 Specialisation = "Machine Design"
	SPEC_MEC2 Specialisation = "Thermal and Fluid Engineering"
	SPEC_MEC3 Specialisation = "Production Engineering"
	SPEC_MEC5 Specialisation = "Decision Science and Engineering"
	SPEC_MET1 Specialisation = "Extractive Metallurgy"
	SPEC_MET2 Specialisation = "Alloy Technology"
	SPEC_MIN1 Specialisation = "Mine Environment"
	SPEC_MIN2 Specialisation = "Rock Mechanics"
	SPEC_MIN3 Specialisation = "Mine Planning"
	SPEC_MST  Specialisation = "Material Science and Technology"
	SPEC_NONE Specialisation = "NONE"
	SPEC_PHE1 Specialisation = "Pharmaceutics"
	SPEC_PHE2 Specialisation = "Pharmaceutical Chemistry"
	SPEC_PHE3 Specialisation = "Pharmacognosy"
	SPEC_PHE4 Specialisation = "Pharmacology"
	SPEC_PHY  Specialisation = "Engineering Physics "
)
